package com.example.mtg.Magic;

public enum Type {
	CREATURE, LAND, ARTIFACT, INSTANT, SORCERY, ENCHANTMENT, PLANESWALKER, TRIBAL, TOKEN, EMBLEM, PLANE, SCHEME, PHENOMENON, VANGUARD, HERO, CONSPIRACY
}
