package com.example.mtg.Helper;

public class Utils {

	public static final String json1 =
			"{\n" + "   \"object\":\"list\",\n" + "   \"total_cards\":267159,\n" + "   \"has_more\":true,\n"
					+ "   \"next_page\":\"https://api.scryfall.com/cards?page=2\",\n" + "   \"data\":[\n" + "      {\n"
					+ "         \"object\":\"card\",\n" + "         \"id\":\"e8fb396f-3ae1-4705-bf94-3e1b0556e910\",\n"
					+ "         \"oracle_id\":\"3c304eaa-09e9-4439-b35d-4b05a54c2fa7\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Acorn Stash\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-02-29\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/e8fb396f-3ae1-4705-bf94-3e1b0556e910\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/tund/6/acorn-stash?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":false,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/e/8/e8fb396f-3ae1-4705-bf94-3e1b0556e910.jpg?1580466464\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/e/8/e8fb396f-3ae1-4705-bf94-3e1b0556e910.jpg?1580466464\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/e/8/e8fb396f-3ae1-4705-bf94-3e1b0556e910.jpg?1580466464\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/e/8/e8fb396f-3ae1-4705-bf94-3e1b0556e910.png?1580466464\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/e/8/e8fb396f-3ae1-4705-bf94-3e1b0556e910.jpg?1580466464\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/e/8/e8fb396f-3ae1-4705-bf94-3e1b0556e910.jpg?1580466464\"\n"
					+ "         },\n" + "         \"mana_cost\":\"\",\n" + "         \"cmc\":0,\n"
					+ "         \"type_line\":\"Card\",\n"
					+ "         \"oracle_text\":\"(Place your acorn counters in this area.)\",\n"
					+ "         \"colors\":[\n" + "\n" + "         ],\n" + "         \"color_identity\":[\n" + "\n"
					+ "         ],\n" + "         \"legalities\":{\n" + "            \"standard\":\"legal\",\n"
					+ "            \"future\":\"not_legal\",\n" + "            \"historic\":\"not_legal\",\n"
					+ "            \"pioneer\":\"not_legal\",\n" + "            \"modern\":\"not_legal\",\n"
					+ "            \"legacy\":\"not_legal\",\n" + "            \"pauper\":\"not_legal\",\n"
					+ "            \"vintage\":\"not_legal\",\n" + "            \"penny\":\"not_legal\",\n"
					+ "            \"commander\":\"not_legal\",\n" + "            \"brawl\":\"not_legal\",\n"
					+ "            \"duel\":\"not_legal\",\n" + "            \"oldschool\":\"not_legal\"\n"
					+ "         },\n" + "         \"games\":[\n" + "            \"paper\"\n" + "         ],\n"
					+ "         \"reserved\":false,\n" + "         \"foil\":false,\n" + "         \"nonfoil\":true,\n"
					+ "         \"oversized\":false,\n" + "         \"promo\":false,\n"
					+ "         \"reprint\":false,\n" + "         \"variation\":false,\n"
					+ "         \"set\":\"tund\",\n" + "         \"set_name\":\"Unsanctioned Tokens\",\n"
					+ "         \"set_type\":\"token\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/8fe3f935-7c8d-4a4e-a051-c0b0f251d262\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Atund&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/tund?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/e8fb396f-3ae1-4705-bf94-3e1b0556e910/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3A3c304eaa-09e9-4439-b35d-4b05a54c2fa7&unique=prints\",\n"
					+ "         \"collector_number\":\"6\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"common\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"\",\n" + "         \"border_color\":\"black\",\n"
					+ "         \"frame\":\"2015\",\n" + "         \"full_art\":false,\n"
					+ "         \"textless\":false,\n" + "         \"booster\":false,\n"
					+ "         \"story_spotlight\":false,\n" + "         \"prices\":{\n"
					+ "            \"usd\":null,\n" + "            \"usd_foil\":null,\n" + "            \"eur\":null,\n"
					+ "            \"tix\":null\n" + "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Acorn+Stash&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Acorn+Stash\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Acorn+Stash\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Acorn+Stash&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Acorn+Stash&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Acorn+Stash&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"628c542b-7579-4070-9143-6f1f7221468f\",\n"
					+ "         \"oracle_id\":\"d82528ac-88f7-4c38-9b1c-c33e6faea532\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Giant Teddy Bear\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-02-29\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/628c542b-7579-4070-9143-6f1f7221468f\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/tund/5/giant-teddy-bear?utm_source=api\",\n"
					+ "         \"layout\":\"token\",\n" + "         \"highres_image\":false,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/6/2/628c542b-7579-4070-9143-6f1f7221468f.jpg?1580466724\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/6/2/628c542b-7579-4070-9143-6f1f7221468f.jpg?1580466724\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/6/2/628c542b-7579-4070-9143-6f1f7221468f.jpg?1580466724\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/6/2/628c542b-7579-4070-9143-6f1f7221468f.png?1580466724\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/6/2/628c542b-7579-4070-9143-6f1f7221468f.jpg?1580466724\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/6/2/628c542b-7579-4070-9143-6f1f7221468f.jpg?1580466724\"\n"
					+ "         },\n" + "         \"mana_cost\":\"\",\n" + "         \"cmc\":0,\n"
					+ "         \"type_line\":\"Token Creature — Giant Teddy Bear\",\n"
					+ "         \"oracle_text\":\"\",\n" + "         \"power\":\"5\",\n"
					+ "         \"toughness\":\"5\",\n" + "         \"colors\":[\n" + "\n" + "         ],\n"
					+ "         \"color_identity\":[\n" + "\n" + "         ],\n" + "         \"all_parts\":[\n"
					+ "            {\n" + "               \"object\":\"related_card\",\n"
					+ "               \"id\":\"628c542b-7579-4070-9143-6f1f7221468f\",\n"
					+ "               \"component\":\"token\",\n" + "               \"name\":\"Giant Teddy Bear\",\n"
					+ "               \"type_line\":\"Token Creature — Giant Teddy Bear\",\n"
					+ "               \"uri\":\"https://api.scryfall.com/cards/628c542b-7579-4070-9143-6f1f7221468f\"\n"
					+ "            },\n" + "            {\n" + "               \"object\":\"related_card\",\n"
					+ "               \"id\":\"242e7c36-8f1a-4614-86c2-07d97cf516fc\",\n"
					+ "               \"component\":\"combo_piece\",\n"
					+ "               \"name\":\"Water Gun Balloon Game\",\n"
					+ "               \"type_line\":\"Artifact\",\n"
					+ "               \"uri\":\"https://api.scryfall.com/cards/242e7c36-8f1a-4614-86c2-07d97cf516fc\"\n"
					+ "            }\n" + "         ],\n" + "         \"legalities\":{\n"
					+ "            \"standard\":\"not_legal\",\n" + "            \"future\":\"not_legal\",\n"
					+ "            \"historic\":\"not_legal\",\n" + "            \"pioneer\":\"not_legal\",\n"
					+ "            \"modern\":\"not_legal\",\n" + "            \"legacy\":\"not_legal\",\n"
					+ "            \"pauper\":\"not_legal\",\n" + "            \"vintage\":\"not_legal\",\n"
					+ "            \"penny\":\"not_legal\",\n" + "            \"commander\":\"not_legal\",\n"
					+ "            \"brawl\":\"not_legal\",\n" + "            \"duel\":\"not_legal\",\n"
					+ "            \"oldschool\":\"not_legal\"\n" + "         },\n" + "         \"games\":[\n"
					+ "            \"paper\"\n" + "         ],\n" + "         \"reserved\":false,\n"
					+ "         \"foil\":false,\n" + "         \"nonfoil\":true,\n" + "         \"oversized\":false,\n"
					+ "         \"promo\":false,\n" + "         \"reprint\":false,\n"
					+ "         \"variation\":false,\n" + "         \"set\":\"tund\",\n"
					+ "         \"set_name\":\"Unsanctioned Tokens\",\n" + "         \"set_type\":\"token\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/8fe3f935-7c8d-4a4e-a051-c0b0f251d262\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Atund&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/tund?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/628c542b-7579-4070-9143-6f1f7221468f/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ad82528ac-88f7-4c38-9b1c-c33e6faea532&unique=prints\",\n"
					+ "         \"collector_number\":\"5\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"common\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Andrea Radeck\",\n" + "         \"artist_ids\":[\n"
					+ "            \"2560b932-96b5-4308-9d32-298641ef326e\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"10a92e1a-b7b9-4655-92a6-99d8bb151301\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"prices\":{\n" + "            \"usd\":null,\n" + "            \"usd_foil\":null,\n"
					+ "            \"eur\":null,\n" + "            \"tix\":null\n" + "         },\n"
					+ "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Giant+Teddy+Bear&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Giant+Teddy+Bear\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Giant+Teddy+Bear\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Giant+Teddy+Bear&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Giant+Teddy+Bear&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Giant+Teddy+Bear&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      }\n" + "   ]\n" + "}";

	public static final String json2 =
			"{\n" + "   \"object\":\"list\",\n" + "   \"total_cards\":267159,\n" + "   \"has_more\":false,\n"
					+ "   \"next_page\":\"null\",\n" + "   \"data\":[\n" + "      {\n"
					+ "         \"object\":\"card\",\n" + "         \"id\":\"f85b4708-e4c7-4115-b353-1d32f4dcff39\",\n"
					+ "         \"oracle_id\":\"0e5e46e3-f9af-47cc-a740-bf808d5cb4b1\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Tectonic Giant\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/f85b4708-e4c7-4115-b353-1d32f4dcff39\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/158s/tectonic-giant?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/f/8/f85b4708-e4c7-4115-b353-1d32f4dcff39.jpg?1579728135\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/f/8/f85b4708-e4c7-4115-b353-1d32f4dcff39.jpg?1579728135\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/f/8/f85b4708-e4c7-4115-b353-1d32f4dcff39.jpg?1579728135\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/f/8/f85b4708-e4c7-4115-b353-1d32f4dcff39.png?1579728135\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/f/8/f85b4708-e4c7-4115-b353-1d32f4dcff39.jpg?1579728135\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/f/8/f85b4708-e4c7-4115-b353-1d32f4dcff39.jpg?1579728135\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{2}{R}{R}\",\n" + "         \"cmc\":4,\n"
					+ "         \"type_line\":\"Creature — Elemental Giant\",\n"
					+ "         \"oracle_text\":\"Whenever Tectonic Giant attacks or becomes the target of a spell an opponent controls, choose one —\\n• Tectonic Giant deals 3 damage to each opponent.\\n• Exile the top two cards of your library. Choose one of them. Until the end of your next turn, you may play that card.\",\n"
					+ "         \"power\":\"3\",\n" + "         \"toughness\":\"4\",\n" + "         \"colors\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"color_identity\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"legalities\":{\n"
					+ "            \"standard\":\"legal\",\n" + "            \"future\":\"legal\",\n"
					+ "            \"historic\":\"legal\",\n" + "            \"pioneer\":\"legal\",\n"
					+ "            \"modern\":\"legal\",\n" + "            \"legacy\":\"legal\",\n"
					+ "            \"pauper\":\"not_legal\",\n" + "            \"vintage\":\"legal\",\n"
					+ "            \"penny\":\"not_legal\",\n" + "            \"commander\":\"legal\",\n"
					+ "            \"brawl\":\"legal\",\n" + "            \"duel\":\"legal\",\n"
					+ "            \"oldschool\":\"not_legal\"\n" + "         },\n" + "         \"games\":[\n"
					+ "            \"paper\"\n" + "         ],\n" + "         \"reserved\":false,\n"
					+ "         \"foil\":true,\n" + "         \"nonfoil\":false,\n" + "         \"oversized\":false,\n"
					+ "         \"promo\":true,\n" + "         \"reprint\":true,\n" + "         \"variation\":false,\n"
					+ "         \"set\":\"pthb\",\n" + "         \"set_name\":\"Theros Beyond Death Promos\",\n"
					+ "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/f85b4708-e4c7-4115-b353-1d32f4dcff39/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0e5e46e3-f9af-47cc-a740-bf808d5cb4b1&unique=prints\",\n"
					+ "         \"collector_number\":\"158s\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Slawomir Maniak\",\n" + "         \"artist_ids\":[\n"
					+ "            \"d887bc66-2779-416c-a1ff-d8720242063e\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"3729e102-ddd5-482c-8a49-95f302edb9e2\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"promo_types\":[\n" + "            \"prerelease\",\n" + "            \"datestamped\"\n"
					+ "         ],\n" + "         \"edhrec_rank\":9348,\n" + "         \"prices\":{\n"
					+ "            \"usd\":null,\n" + "            \"usd_foil\":null,\n" + "            \"eur\":null,\n"
					+ "            \"tix\":null\n" + "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Tectonic+Giant&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Tectonic+Giant\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Tectonic+Giant\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Tectonic+Giant&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Tectonic+Giant&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Tectonic+Giant&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5\",\n"
					+ "         \"oracle_id\":\"0e5e46e3-f9af-47cc-a740-bf808d5cb4b1\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Tectonic Giant\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/158p/tectonic-giant?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/6/9/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5.jpg?1579729716\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/6/9/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5.jpg?1579729716\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/6/9/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5.jpg?1579729716\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/6/9/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5.png?1579729716\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/6/9/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5.jpg?1579729716\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/6/9/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5.jpg?1579729716\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{2}{R}{R}\",\n" + "         \"cmc\":4,\n"
					+ "         \"type_line\":\"Creature — Elemental Giant\",\n"
					+ "         \"oracle_text\":\"Whenever Tectonic Giant attacks or becomes the target of a spell an opponent controls, choose one —\\n• Tectonic Giant deals 3 damage to each opponent.\\n• Exile the top two cards of your library. Choose one of them. Until the end of your next turn, you may play that card.\",\n"
					+ "         \"power\":\"3\",\n" + "         \"toughness\":\"4\",\n" + "         \"colors\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"color_identity\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"legalities\":{\n"
					+ "            \"standard\":\"legal\",\n" + "            \"future\":\"legal\",\n"
					+ "            \"historic\":\"legal\",\n" + "            \"pioneer\":\"legal\",\n"
					+ "            \"modern\":\"legal\",\n" + "            \"legacy\":\"legal\",\n"
					+ "            \"pauper\":\"not_legal\",\n" + "            \"vintage\":\"legal\",\n"
					+ "            \"penny\":\"not_legal\",\n" + "            \"commander\":\"legal\",\n"
					+ "            \"brawl\":\"legal\",\n" + "            \"duel\":\"legal\",\n"
					+ "            \"oldschool\":\"not_legal\"\n" + "         },\n" + "         \"games\":[\n"
					+ "            \"paper\"\n" + "         ],\n" + "         \"reserved\":false,\n"
					+ "         \"foil\":true,\n" + "         \"nonfoil\":true,\n" + "         \"oversized\":false,\n"
					+ "         \"promo\":true,\n" + "         \"reprint\":true,\n" + "         \"variation\":false,\n"
					+ "         \"set\":\"pthb\",\n" + "         \"set_name\":\"Theros Beyond Death Promos\",\n"
					+ "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/693e0e95-55b7-4224-b2ce-4d3a5c0ddcb5/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3A0e5e46e3-f9af-47cc-a740-bf808d5cb4b1&unique=prints\",\n"
					+ "         \"collector_number\":\"158p\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Slawomir Maniak\",\n" + "         \"artist_ids\":[\n"
					+ "            \"d887bc66-2779-416c-a1ff-d8720242063e\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"3729e102-ddd5-482c-8a49-95f302edb9e2\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"edhrec_rank\":9348,\n" + "         \"prices\":{\n" + "            \"usd\":null,\n"
					+ "            \"usd_foil\":null,\n" + "            \"eur\":null,\n" + "            \"tix\":null\n"
					+ "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Tectonic+Giant&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Tectonic+Giant\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Tectonic+Giant\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Tectonic+Giant&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Tectonic+Giant&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Tectonic+Giant&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73\",\n"
					+ "         \"oracle_id\":\"eeb6f5eb-0e16-468e-9dfe-6ec8d8172f86\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Storm's Wrath\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/157s/storms-wrath?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/e/5/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73.jpg?1579728142\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/e/5/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73.jpg?1579728142\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/e/5/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73.jpg?1579728142\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/e/5/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73.png?1579728142\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/e/5/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73.jpg?1579728142\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/e/5/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73.jpg?1579728142\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{2}{R}{R}\",\n" + "         \"cmc\":4,\n"
					+ "         \"type_line\":\"Sorcery\",\n"
					+ "         \"oracle_text\":\"Storm's Wrath deals 4 damage to each creature and each planeswalker.\",\n"
					+ "         \"colors\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"color_identity\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"legalities\":{\n" + "            \"standard\":\"legal\",\n"
					+ "            \"future\":\"legal\",\n" + "            \"historic\":\"legal\",\n"
					+ "            \"pioneer\":\"legal\",\n" + "            \"modern\":\"legal\",\n"
					+ "            \"legacy\":\"legal\",\n" + "            \"pauper\":\"not_legal\",\n"
					+ "            \"vintage\":\"legal\",\n" + "            \"penny\":\"not_legal\",\n"
					+ "            \"commander\":\"legal\",\n" + "            \"brawl\":\"legal\",\n"
					+ "            \"duel\":\"legal\",\n" + "            \"oldschool\":\"not_legal\"\n"
					+ "         },\n" + "         \"games\":[\n" + "            \"paper\"\n" + "         ],\n"
					+ "         \"reserved\":false,\n" + "         \"foil\":true,\n" + "         \"nonfoil\":false,\n"
					+ "         \"oversized\":false,\n" + "         \"promo\":true,\n" + "         \"reprint\":true,\n"
					+ "         \"variation\":false,\n" + "         \"set\":\"pthb\",\n"
					+ "         \"set_name\":\"Theros Beyond Death Promos\",\n" + "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/e53bb24f-e04c-4ab1-a40b-5f3ac30d4c73/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aeeb6f5eb-0e16-468e-9dfe-6ec8d8172f86&unique=prints\",\n"
					+ "         \"collector_number\":\"157s\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"flavor_text\":\"Distant thunder rumbled, a dread forewarning of Keranos's displeasure.\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Yeong-Hao Han\",\n" + "         \"artist_ids\":[\n"
					+ "            \"f8e7f8d6-6dde-4059-973c-30f1fd1bbe4e\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"17a010d0-4cc1-4f7d-bbd7-e665bb2325f0\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"promo_types\":[\n" + "            \"prerelease\",\n" + "            \"datestamped\"\n"
					+ "         ],\n" + "         \"edhrec_rank\":10531,\n" + "         \"prices\":{\n"
					+ "            \"usd\":null,\n" + "            \"usd_foil\":null,\n" + "            \"eur\":null,\n"
					+ "            \"tix\":null\n" + "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Storm%27s+Wrath&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Storm%27s+Wrath\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Storm%27s+Wrath\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Storm%27s+Wrath&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Storm%27s+Wrath&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Storm%27s+Wrath&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"b77e7561-b324-4137-aba6-237736a7231a\",\n"
					+ "         \"oracle_id\":\"eeb6f5eb-0e16-468e-9dfe-6ec8d8172f86\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Storm's Wrath\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/b77e7561-b324-4137-aba6-237736a7231a\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/157p/storms-wrath?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/b/7/b77e7561-b324-4137-aba6-237736a7231a.jpg?1579729719\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/b/7/b77e7561-b324-4137-aba6-237736a7231a.jpg?1579729719\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/b/7/b77e7561-b324-4137-aba6-237736a7231a.jpg?1579729719\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/b/7/b77e7561-b324-4137-aba6-237736a7231a.png?1579729719\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/b/7/b77e7561-b324-4137-aba6-237736a7231a.jpg?1579729719\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/b/7/b77e7561-b324-4137-aba6-237736a7231a.jpg?1579729719\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{2}{R}{R}\",\n" + "         \"cmc\":4,\n"
					+ "         \"type_line\":\"Sorcery\",\n"
					+ "         \"oracle_text\":\"Storm's Wrath deals 4 damage to each creature and each planeswalker.\",\n"
					+ "         \"colors\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"color_identity\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"legalities\":{\n" + "            \"standard\":\"legal\",\n"
					+ "            \"future\":\"legal\",\n" + "            \"historic\":\"legal\",\n"
					+ "            \"pioneer\":\"legal\",\n" + "            \"modern\":\"legal\",\n"
					+ "            \"legacy\":\"legal\",\n" + "            \"pauper\":\"not_legal\",\n"
					+ "            \"vintage\":\"legal\",\n" + "            \"penny\":\"not_legal\",\n"
					+ "            \"commander\":\"legal\",\n" + "            \"brawl\":\"legal\",\n"
					+ "            \"duel\":\"legal\",\n" + "            \"oldschool\":\"not_legal\"\n"
					+ "         },\n" + "         \"games\":[\n" + "            \"paper\"\n" + "         ],\n"
					+ "         \"reserved\":false,\n" + "         \"foil\":true,\n" + "         \"nonfoil\":true,\n"
					+ "         \"oversized\":false,\n" + "         \"promo\":true,\n" + "         \"reprint\":true,\n"
					+ "         \"variation\":false,\n" + "         \"set\":\"pthb\",\n"
					+ "         \"set_name\":\"Theros Beyond Death Promos\",\n" + "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/b77e7561-b324-4137-aba6-237736a7231a/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3Aeeb6f5eb-0e16-468e-9dfe-6ec8d8172f86&unique=prints\",\n"
					+ "         \"collector_number\":\"157p\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"flavor_text\":\"Distant thunder rumbled, a dread forewarning of Keranos's displeasure.\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Yeong-Hao Han\",\n" + "         \"artist_ids\":[\n"
					+ "            \"f8e7f8d6-6dde-4059-973c-30f1fd1bbe4e\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"17a010d0-4cc1-4f7d-bbd7-e665bb2325f0\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"edhrec_rank\":10531,\n" + "         \"prices\":{\n" + "            \"usd\":null,\n"
					+ "            \"usd_foil\":null,\n" + "            \"eur\":null,\n" + "            \"tix\":null\n"
					+ "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Storm%27s+Wrath&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Storm%27s+Wrath\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Storm%27s+Wrath\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Storm%27s+Wrath&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Storm%27s+Wrath&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Storm%27s+Wrath&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f\",\n"
					+ "         \"oracle_id\":\"1692602a-0c44-485c-aadc-c9c70ed70ea8\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Storm Herald\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/156s/storm-herald?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/e/5/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f.jpg?1579728149\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/e/5/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f.jpg?1579728149\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/e/5/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f.jpg?1579728149\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/e/5/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f.png?1579728149\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/e/5/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f.jpg?1579728149\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/e/5/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f.jpg?1579728149\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{2}{R}\",\n" + "         \"cmc\":3,\n"
					+ "         \"type_line\":\"Creature — Human Shaman\",\n"
					+ "         \"oracle_text\":\"Haste\\nWhen Storm Herald enters the battlefield, return any number of Aura cards from your graveyard to the battlefield attached to creatures you control. Exile those Auras at the beginning of your next end step. If those Auras would leave the battlefield, exile them instead of putting them anywhere else.\",\n"
					+ "         \"power\":\"3\",\n" + "         \"toughness\":\"2\",\n" + "         \"colors\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"color_identity\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"legalities\":{\n"
					+ "            \"standard\":\"legal\",\n" + "            \"future\":\"legal\",\n"
					+ "            \"historic\":\"legal\",\n" + "            \"pioneer\":\"legal\",\n"
					+ "            \"modern\":\"legal\",\n" + "            \"legacy\":\"legal\",\n"
					+ "            \"pauper\":\"not_legal\",\n" + "            \"vintage\":\"legal\",\n"
					+ "            \"penny\":\"not_legal\",\n" + "            \"commander\":\"legal\",\n"
					+ "            \"brawl\":\"legal\",\n" + "            \"duel\":\"legal\",\n"
					+ "            \"oldschool\":\"not_legal\"\n" + "         },\n" + "         \"games\":[\n"
					+ "            \"paper\"\n" + "         ],\n" + "         \"reserved\":false,\n"
					+ "         \"foil\":true,\n" + "         \"nonfoil\":false,\n" + "         \"oversized\":false,\n"
					+ "         \"promo\":true,\n" + "         \"reprint\":true,\n" + "         \"variation\":false,\n"
					+ "         \"set\":\"pthb\",\n" + "         \"set_name\":\"Theros Beyond Death Promos\",\n"
					+ "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/e5e68a2c-c3fd-4797-b9e6-856fe1e1d34f/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3A1692602a-0c44-485c-aadc-c9c70ed70ea8&unique=prints\",\n"
					+ "         \"collector_number\":\"156s\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Aleksi Briclot\",\n" + "         \"artist_ids\":[\n"
					+ "            \"5e470014-31cb-41b0-b054-e23374484449\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"1acb6c0d-3ccf-4e8f-bb72-735b1bf9f472\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"promo_types\":[\n" + "            \"prerelease\",\n" + "            \"datestamped\"\n"
					+ "         ],\n" + "         \"edhrec_rank\":17570,\n" + "         \"prices\":{\n"
					+ "            \"usd\":null,\n" + "            \"usd_foil\":null,\n" + "            \"eur\":null,\n"
					+ "            \"tix\":null\n" + "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Storm+Herald&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Storm+Herald\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Storm+Herald\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Storm+Herald&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Storm+Herald&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Storm+Herald&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"62c4aba2-195d-47f5-8b6a-bd925522ea84\",\n"
					+ "         \"oracle_id\":\"1692602a-0c44-485c-aadc-c9c70ed70ea8\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Storm Herald\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/62c4aba2-195d-47f5-8b6a-bd925522ea84\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/156p/storm-herald?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/6/2/62c4aba2-195d-47f5-8b6a-bd925522ea84.jpg?1579729721\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/6/2/62c4aba2-195d-47f5-8b6a-bd925522ea84.jpg?1579729721\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/6/2/62c4aba2-195d-47f5-8b6a-bd925522ea84.jpg?1579729721\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/6/2/62c4aba2-195d-47f5-8b6a-bd925522ea84.png?1579729721\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/6/2/62c4aba2-195d-47f5-8b6a-bd925522ea84.jpg?1579729721\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/6/2/62c4aba2-195d-47f5-8b6a-bd925522ea84.jpg?1579729721\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{2}{R}\",\n" + "         \"cmc\":3,\n"
					+ "         \"type_line\":\"Creature — Human Shaman\",\n"
					+ "         \"oracle_text\":\"Haste\\nWhen Storm Herald enters the battlefield, return any number of Aura cards from your graveyard to the battlefield attached to creatures you control. Exile those Auras at the beginning of your next end step. If those Auras would leave the battlefield, exile them instead of putting them anywhere else.\",\n"
					+ "         \"power\":\"3\",\n" + "         \"toughness\":\"2\",\n" + "         \"colors\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"color_identity\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"legalities\":{\n"
					+ "            \"standard\":\"legal\",\n" + "            \"future\":\"legal\",\n"
					+ "            \"historic\":\"legal\",\n" + "            \"pioneer\":\"legal\",\n"
					+ "            \"modern\":\"legal\",\n" + "            \"legacy\":\"legal\",\n"
					+ "            \"pauper\":\"not_legal\",\n" + "            \"vintage\":\"legal\",\n"
					+ "            \"penny\":\"not_legal\",\n" + "            \"commander\":\"legal\",\n"
					+ "            \"brawl\":\"legal\",\n" + "            \"duel\":\"legal\",\n"
					+ "            \"oldschool\":\"not_legal\"\n" + "         },\n" + "         \"games\":[\n"
					+ "            \"paper\"\n" + "         ],\n" + "         \"reserved\":false,\n"
					+ "         \"foil\":true,\n" + "         \"nonfoil\":true,\n" + "         \"oversized\":false,\n"
					+ "         \"promo\":true,\n" + "         \"reprint\":true,\n" + "         \"variation\":false,\n"
					+ "         \"set\":\"pthb\",\n" + "         \"set_name\":\"Theros Beyond Death Promos\",\n"
					+ "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/62c4aba2-195d-47f5-8b6a-bd925522ea84/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3A1692602a-0c44-485c-aadc-c9c70ed70ea8&unique=prints\",\n"
					+ "         \"collector_number\":\"156p\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Aleksi Briclot\",\n" + "         \"artist_ids\":[\n"
					+ "            \"5e470014-31cb-41b0-b054-e23374484449\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"1acb6c0d-3ccf-4e8f-bb72-735b1bf9f472\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"edhrec_rank\":17570,\n" + "         \"prices\":{\n" + "            \"usd\":null,\n"
					+ "            \"usd_foil\":null,\n" + "            \"eur\":null,\n" + "            \"tix\":null\n"
					+ "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Storm+Herald&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Storm+Herald\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Storm+Herald\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Storm+Herald&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Storm+Herald&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Storm+Herald&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"5a1dd544-e8d5-40f5-a61b-9e1b98a9f985\",\n"
					+ "         \"oracle_id\":\"e190f086-ebee-447f-907f-7b37ec8824ac\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Purphoros's Intervention\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/151s/purphoross-intervention?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/5/a/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985.jpg?1579728158\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/5/a/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985.jpg?1579728158\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/5/a/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985.jpg?1579728158\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/5/a/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985.png?1579728158\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/5/a/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985.jpg?1579728158\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/5/a/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985.jpg?1579728158\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{X}{R}\",\n" + "         \"cmc\":1,\n"
					+ "         \"type_line\":\"Sorcery\",\n"
					+ "         \"oracle_text\":\"Choose one —\\n• Create an X/1 red Elemental creature token with trample and haste. Sacrifice it at the beginning of the next end step.\\n• Purphoros's Intervention deals twice X damage to target creature or planeswalker.\",\n"
					+ "         \"colors\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"color_identity\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"legalities\":{\n" + "            \"standard\":\"legal\",\n"
					+ "            \"future\":\"legal\",\n" + "            \"historic\":\"legal\",\n"
					+ "            \"pioneer\":\"legal\",\n" + "            \"modern\":\"legal\",\n"
					+ "            \"legacy\":\"legal\",\n" + "            \"pauper\":\"not_legal\",\n"
					+ "            \"vintage\":\"legal\",\n" + "            \"penny\":\"not_legal\",\n"
					+ "            \"commander\":\"legal\",\n" + "            \"brawl\":\"legal\",\n"
					+ "            \"duel\":\"legal\",\n" + "            \"oldschool\":\"not_legal\"\n"
					+ "         },\n" + "         \"games\":[\n" + "            \"paper\"\n" + "         ],\n"
					+ "         \"reserved\":false,\n" + "         \"foil\":true,\n" + "         \"nonfoil\":false,\n"
					+ "         \"oversized\":false,\n" + "         \"promo\":true,\n" + "         \"reprint\":true,\n"
					+ "         \"variation\":false,\n" + "         \"set\":\"pthb\",\n"
					+ "         \"set_name\":\"Theros Beyond Death Promos\",\n" + "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/5a1dd544-e8d5-40f5-a61b-9e1b98a9f985/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ae190f086-ebee-447f-907f-7b37ec8824ac&unique=prints\",\n"
					+ "         \"collector_number\":\"151s\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"flavor_text\":\"\\\"I bring a fire to recast all the world.\\\"\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Aleksi Briclot\",\n" + "         \"artist_ids\":[\n"
					+ "            \"5e470014-31cb-41b0-b054-e23374484449\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"08902056-9598-483c-a8d3-eec32186defa\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"promo_types\":[\n" + "            \"prerelease\",\n" + "            \"datestamped\"\n"
					+ "         ],\n" + "         \"edhrec_rank\":13637,\n" + "         \"prices\":{\n"
					+ "            \"usd\":null,\n" + "            \"usd_foil\":null,\n" + "            \"eur\":null,\n"
					+ "            \"tix\":null\n" + "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Purphoros%27s+Intervention&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Purphoros%27s+Intervention\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Purphoros%27s+Intervention\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Purphoros%27s+Intervention&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Purphoros%27s+Intervention&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Purphoros%27s+Intervention&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"01be13b4-aa80-4250-82e8-96ec7f860111\",\n"
					+ "         \"oracle_id\":\"e190f086-ebee-447f-907f-7b37ec8824ac\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Purphoros's Intervention\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/01be13b4-aa80-4250-82e8-96ec7f860111\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/151p/purphoross-intervention?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/0/1/01be13b4-aa80-4250-82e8-96ec7f860111.jpg?1579729724\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/0/1/01be13b4-aa80-4250-82e8-96ec7f860111.jpg?1579729724\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/0/1/01be13b4-aa80-4250-82e8-96ec7f860111.jpg?1579729724\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/0/1/01be13b4-aa80-4250-82e8-96ec7f860111.png?1579729724\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/0/1/01be13b4-aa80-4250-82e8-96ec7f860111.jpg?1579729724\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/0/1/01be13b4-aa80-4250-82e8-96ec7f860111.jpg?1579729724\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{X}{R}\",\n" + "         \"cmc\":1,\n"
					+ "         \"type_line\":\"Sorcery\",\n"
					+ "         \"oracle_text\":\"Choose one —\\n• Create an X/1 red Elemental creature token with trample and haste. Sacrifice it at the beginning of the next end step.\\n• Purphoros's Intervention deals twice X damage to target creature or planeswalker.\",\n"
					+ "         \"colors\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"color_identity\":[\n" + "            \"R\"\n" + "         ],\n"
					+ "         \"legalities\":{\n" + "            \"standard\":\"legal\",\n"
					+ "            \"future\":\"legal\",\n" + "            \"historic\":\"legal\",\n"
					+ "            \"pioneer\":\"legal\",\n" + "            \"modern\":\"legal\",\n"
					+ "            \"legacy\":\"legal\",\n" + "            \"pauper\":\"not_legal\",\n"
					+ "            \"vintage\":\"legal\",\n" + "            \"penny\":\"not_legal\",\n"
					+ "            \"commander\":\"legal\",\n" + "            \"brawl\":\"legal\",\n"
					+ "            \"duel\":\"legal\",\n" + "            \"oldschool\":\"not_legal\"\n"
					+ "         },\n" + "         \"games\":[\n" + "            \"paper\"\n" + "         ],\n"
					+ "         \"reserved\":false,\n" + "         \"foil\":true,\n" + "         \"nonfoil\":true,\n"
					+ "         \"oversized\":false,\n" + "         \"promo\":true,\n" + "         \"reprint\":true,\n"
					+ "         \"variation\":false,\n" + "         \"set\":\"pthb\",\n"
					+ "         \"set_name\":\"Theros Beyond Death Promos\",\n" + "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/01be13b4-aa80-4250-82e8-96ec7f860111/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3Ae190f086-ebee-447f-907f-7b37ec8824ac&unique=prints\",\n"
					+ "         \"collector_number\":\"151p\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"rare\",\n"
					+ "         \"flavor_text\":\"\\\"I bring a fire to recast all the world.\\\"\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Aleksi Briclot\",\n" + "         \"artist_ids\":[\n"
					+ "            \"5e470014-31cb-41b0-b054-e23374484449\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"08902056-9598-483c-a8d3-eec32186defa\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"edhrec_rank\":13637,\n" + "         \"prices\":{\n" + "            \"usd\":null,\n"
					+ "            \"usd_foil\":null,\n" + "            \"eur\":null,\n" + "            \"tix\":null\n"
					+ "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Purphoros%27s+Intervention&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Purphoros%27s+Intervention\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Purphoros%27s+Intervention\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Purphoros%27s+Intervention&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Purphoros%27s+Intervention&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Purphoros%27s+Intervention&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      },\n" + "      {\n" + "         \"object\":\"card\",\n"
					+ "         \"id\":\"18d3e962-bf24-4a7d-a21f-9a2628af54cf\",\n"
					+ "         \"oracle_id\":\"6728b9d0-d3ab-4ba3-af13-63cb83e0ed99\",\n"
					+ "         \"multiverse_ids\":[\n" + "\n" + "         ],\n"
					+ "         \"name\":\"Purphoros, Bronze-Blooded\",\n" + "         \"lang\":\"en\",\n"
					+ "         \"released_at\":\"2020-01-24\",\n"
					+ "         \"uri\":\"https://api.scryfall.com/cards/18d3e962-bf24-4a7d-a21f-9a2628af54cf\",\n"
					+ "         \"scryfall_uri\":\"https://scryfall.com/card/pthb/150s/purphoros-bronze-blooded?utm_source=api\",\n"
					+ "         \"layout\":\"normal\",\n" + "         \"highres_image\":true,\n"
					+ "         \"image_uris\":{\n"
					+ "            \"small\":\"https://img.scryfall.com/cards/small/front/1/8/18d3e962-bf24-4a7d-a21f-9a2628af54cf.jpg?1579728166\",\n"
					+ "            \"normal\":\"https://img.scryfall.com/cards/normal/front/1/8/18d3e962-bf24-4a7d-a21f-9a2628af54cf.jpg?1579728166\",\n"
					+ "            \"large\":\"https://img.scryfall.com/cards/large/front/1/8/18d3e962-bf24-4a7d-a21f-9a2628af54cf.jpg?1579728166\",\n"
					+ "            \"png\":\"https://img.scryfall.com/cards/png/front/1/8/18d3e962-bf24-4a7d-a21f-9a2628af54cf.png?1579728166\",\n"
					+ "            \"art_crop\":\"https://img.scryfall.com/cards/art_crop/front/1/8/18d3e962-bf24-4a7d-a21f-9a2628af54cf.jpg?1579728166\",\n"
					+ "            \"border_crop\":\"https://img.scryfall.com/cards/border_crop/front/1/8/18d3e962-bf24-4a7d-a21f-9a2628af54cf.jpg?1579728166\"\n"
					+ "         },\n" + "         \"mana_cost\":\"{4}{R}\",\n" + "         \"cmc\":5,\n"
					+ "         \"type_line\":\"Legendary Enchantment Creature — God\",\n"
					+ "         \"oracle_text\":\"Indestructible\\nAs long as your devotion to red is less than five, Purphoros isn't a creature.\\nOther creatures you control have haste.\\n{2}{R}: You may put a red creature card or an artifact creature card from your hand onto the battlefield. Sacrifice it at the beginning of the next end step.\",\n"
					+ "         \"power\":\"7\",\n" + "         \"toughness\":\"6\",\n" + "         \"colors\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"color_identity\":[\n"
					+ "            \"R\"\n" + "         ],\n" + "         \"legalities\":{\n"
					+ "            \"standard\":\"legal\",\n" + "            \"future\":\"legal\",\n"
					+ "            \"historic\":\"legal\",\n" + "            \"pioneer\":\"legal\",\n"
					+ "            \"modern\":\"legal\",\n" + "            \"legacy\":\"legal\",\n"
					+ "            \"pauper\":\"not_legal\",\n" + "            \"vintage\":\"legal\",\n"
					+ "            \"penny\":\"not_legal\",\n" + "            \"commander\":\"legal\",\n"
					+ "            \"brawl\":\"legal\",\n" + "            \"duel\":\"legal\",\n"
					+ "            \"oldschool\":\"not_legal\"\n" + "         },\n" + "         \"games\":[\n"
					+ "            \"paper\"\n" + "         ],\n" + "         \"reserved\":false,\n"
					+ "         \"foil\":true,\n" + "         \"nonfoil\":false,\n" + "         \"oversized\":false,\n"
					+ "         \"promo\":true,\n" + "         \"reprint\":true,\n" + "         \"variation\":false,\n"
					+ "         \"set\":\"pthb\",\n" + "         \"set_name\":\"Theros Beyond Death Promos\",\n"
					+ "         \"set_type\":\"promo\",\n"
					+ "         \"set_uri\":\"https://api.scryfall.com/sets/66d787e4-101d-4f72-a4ed-7c38df9b99fe\",\n"
					+ "         \"set_search_uri\":\"https://api.scryfall.com/cards/search?order=set&q=e%3Apthb&unique=prints\",\n"
					+ "         \"scryfall_set_uri\":\"https://scryfall.com/sets/pthb?utm_source=api\",\n"
					+ "         \"rulings_uri\":\"https://api.scryfall.com/cards/18d3e962-bf24-4a7d-a21f-9a2628af54cf/rulings\",\n"
					+ "         \"prints_search_uri\":\"https://api.scryfall.com/cards/search?order=released&q=oracleid%3A6728b9d0-d3ab-4ba3-af13-63cb83e0ed99&unique=prints\",\n"
					+ "         \"collector_number\":\"150s\",\n" + "         \"digital\":false,\n"
					+ "         \"rarity\":\"mythic\",\n"
					+ "         \"card_back_id\":\"0aeebaf5-8c7d-4636-9e82-8c27447861f7\",\n"
					+ "         \"artist\":\"Eric Deschamps\",\n" + "         \"artist_ids\":[\n"
					+ "            \"37970e22-9cee-44c1-af44-5ee27cf26b76\"\n" + "         ],\n"
					+ "         \"illustration_id\":\"a0b5d84b-a4f7-4aed-9265-071b23c2b51e\",\n"
					+ "         \"border_color\":\"black\",\n" + "         \"frame\":\"2015\",\n"
					+ "         \"frame_effects\":[\n" + "            \"legendary\"\n" + "         ],\n"
					+ "         \"full_art\":false,\n" + "         \"textless\":false,\n"
					+ "         \"booster\":false,\n" + "         \"story_spotlight\":false,\n"
					+ "         \"promo_types\":[\n" + "            \"prerelease\",\n" + "            \"datestamped\"\n"
					+ "         ],\n" + "         \"edhrec_rank\":7437,\n" + "         \"prices\":{\n"
					+ "            \"usd\":null,\n" + "            \"usd_foil\":null,\n" + "            \"eur\":null,\n"
					+ "            \"tix\":null\n" + "         },\n" + "         \"related_uris\":{\n"
					+ "            \"tcgplayer_decks\":\"https://decks.tcgplayer.com/magic/deck/search?contains=Purphoros%2C+Bronze-Blooded&page=1&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"edhrec\":\"https://edhrec.com/route/?cc=Purphoros%2C+Bronze-Blooded\",\n"
					+ "            \"mtgtop8\":\"https://mtgtop8.com/search?MD_check=1&SB_check=1&cards=Purphoros%2C+Bronze-Blooded\"\n"
					+ "         },\n" + "         \"purchase_uris\":{\n"
					+ "            \"tcgplayer\":\"https://shop.tcgplayer.com/productcatalog/product/show?ProductName=Purphoros%2C+Bronze-Blooded&partner=Scryfall&utm_campaign=affiliate&utm_medium=scryfall&utm_source=scryfall\",\n"
					+ "            \"cardmarket\":\"https://www.cardmarket.com/en/Magic/Products/Search?referrer=scryfall&searchString=Purphoros%2C+Bronze-Blooded&utm_campaign=card_prices&utm_medium=text&utm_source=scryfall\",\n"
					+ "            \"cardhoarder\":\"https://www.cardhoarder.com/cards?affiliate_id=scryfall&data%5Bsearch%5D=Purphoros%2C+Bronze-Blooded&ref=card-profile&utm_campaign=affiliate&utm_medium=card&utm_source=scryfall\"\n"
					+ "         }\n" + "      }\n" + "   ]\n" + "}";
}
